### ISSUE TITLE
ServiceInstance labels not displayed for cloud-storage 

### ISSUE THREAD

**Issue by nabadger** [GoogleCloudPlatform/gcp-service-broker#209]
I have a ServiceInstance manifest for a `cloud-storage` class, and I was expecting that if labels were supplied, they would be visible on the GCP console (when browsing bucket resources).

Example k8s manifest:
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sc-bucket-test-with-labels
  namespace: test
spec:
  clusterServiceClassExternalName: cloud-storage
  clusterServicePlanExternalName: beta
  parameters:
    bucketId: sc-bucket-test-with-labels
    location: EU
    storageclass: MULTI_REGION
    labels:
      mylabelname: mylabelvalue
```

I don't see a reference to `mylabelname` anywhere when browsing the Bucket via the Storage section of console.cloud.google.com

I do however see an auto-generated label in the format `goog-dm : i4....`

I'm wondering whether this is expected behaviour, a bug, or if I'm specifying the labels incorrectly?

Thanks
