### ISSUE TITLE
Split documentation about the ServiceClasses

### ISSUE THREAD

**Issue by polskikiel** [GoogleCloudPlatform/gcp-service-broker#497]
We'd love to have this [document](https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/docs/use.md) split per ServiceClass. 

It would help us to expose the GCP broker classes to our customers with the documentation per ServiceClass provided from this repository to keep it always updated with the broker offerings.

**Comment by mszostok** [comment]
Basically, the Azure and AWS brokers have that information split per file:
- AWS: https://github.com/awslabs/aws-servicebroker/tree/master/templates/
- Azure: https://github.com/Azure/open-service-broker-azure/tree/master/docs/modules

Thanks to that it's easier to find and reference to a single service class.
What's more in [Kyma CNCF](https://kyma-project.io) project we are able to download them and display in Service Catalog UI using such defintion:
```yaml
apiVersion: cms.kyma-project.io/v1alpha1
kind: DocsTopic
metadata:
  name: 3dc60f71-bfed-518e-95c5-a16c0017b591
  labels:
    cms.kyma-project.io/view-context: service-catalog
spec:
  sources:
    - type: markdown
      name: athena-readme
      mode: single
      url: "https://raw.githubusercontent.com/awslabs/aws-servicebroker/v1.0.1/templates/athena/README.md"
```
and UI:
<img width="1331" alt="docs-view" src="https://user-images.githubusercontent.com/17568639/63604574-734df580-c5cc-11e9-8fe7-3134e7debd53.png">


Unfortunately, for the GCP broker, we were forced to split the [use.md](https://github.com/GoogleCloudPlatform/gcp-service-broker/tree/master/docs) file by our own and commit them to [our repository](https://github.com/kyma-project/addons/tree/master/addons/google-cloud-platform-service-broker-0.1.0/docs)

But it's not easy to have them always in sync. Better is refer directly to your documentation:)

I've prepared the pull-request to show you what kind of changes needs to be made. Additionally, the ToC is generated thanks to that looking for given Service Class is much easier instead of scrolling single file which contains more than 2k lines. More info can be found directly in [PR](https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/521) :)


/cc @josephlewis42
